# Generated by Django 3.2.7 on 2021-09-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='url_pair',
            new_name='UrlPair',
        ),
    ]
